# Generated by Django 3.2.6 on 2021-08-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='registration',
            name='password2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
