# Generated by Django 3.2.6 on 2021-08-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_registration_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='password2',
        ),
    ]
