# Generated by Django 3.2.6 on 2021-08-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_registration_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[(None, 'Choose your gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phoneno', models.CharField(max_length=12)),
                ('experience', models.CharField(max_length=10)),
                ('workfield', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
