# Generated by Django 3.2.6 on 2021-08-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_doctorregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregistration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
