# Generated by Django 3.2.6 on 2021-08-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20210817_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorregistration',
            name='mob_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='mob_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
