# Generated by Django 3.2.6 on 2021-08-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='pid',
            field=models.CharField(default='00000', max_length=100),
        ),
    ]
