# Generated by Django 3.2.6 on 2021-08-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_otpverification_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='patid',
            field=models.CharField(default='', max_length=100),
        ),
    ]
